- name: Test
  hosts: localhost
  gather_facts: False
  tasks:
    - name: debug_read_collections_path
      ansible.builtin.debug:
        msg: "{{ lookup('config', 'COLLECTIONS_PATHS') }}"
      run_once: true
      register: reg_debug_read_collections_path

    - command: ansible-galaxy collection install containers.podman -p .

    - reload_collections:
        name: "eps"
    - include_tasks: configs/b/main.yaml

- name: Test2
  hosts: localhost
  collections:
    - kubernetes.kubevirt
  tasks:
    - include_tasks: configs/a/main.yaml
