- name: Test
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Show collections path
      ansible.builtin.debug:
        msg: "{{ lookup('config', 'COLLECTIONS_PATHS') }}"

    - command: ansible-galaxy collection install community.okd
    - include_tasks: configs/b/main.yaml
