- name: Test
  hosts: localhost
  tasks:
    - name: debug_read_collections_path
      ansible.builtin.debug:
        msg: "{{ lookup('config', 'COLLECTIONS_PATHS') }}"
      run_once: true
      register: reg_debug_read_collections_path
    - command: ansible-galaxy collection install -r configs/a/requirements.yaml -p /home/runner/.ansible/collections

- name: Test2
  hosts: localhost
  collections:
    - kubernetes.kubevirt
  tasks:
    - include_tasks: configs/a/main.yaml
